// src/services/code/generateProjectCode.js

import { getLanguageConfig } from "../../languageRegistry"
import { elementRegistry } from "../../../libs/elementRegistry"

/**
 * Gera o código LaTeX completo do projeto (preamble + ambiente + corpo).
 * 100% direcionado por project.type e pelos descriptors da lib.
 *
 * @param {object} project - { type, name, ... }
 * @param {Array<object>} elements - elementos da store (já filtrados por workspace, se for o caso)
 * @returns {string} código LaTeX completo
 */
export function generateProjectCode(project, elements) {
  const lang = getLanguageConfig(project?.type)
  const projectName = project?.name || 'Untitled'
  const env = lang.environment || 'tikzpicture'
  const pkgs = Array.isArray(lang.requiredPackages) ? lang.requiredPackages : ['tikz']

  // ===== PREÂMBULO DINÂMICO =====
  const preambleLines = [
    '% Auto-generated by incide',
    '\\documentclass{standalone}',
    ...pkgs.map((pkg) => `\\usepackage{${pkg}}`),
    '',
  ]

  // ===== CORPO DO AMBIENTE =====
  const bodyLines = []

  // Ordena elementos opcionalmente por zIndex (se existir)
  const sortedElements = [...(elements || [])].sort((a, b) => {
    const za = typeof a.zIndex === 'number' ? a.zIndex : 0
    const zb = typeof b.zIndex === 'number' ? b.zIndex : 0
    return za - zb
  })

  sortedElements.forEach((elem, index) => {
    const desc = elementRegistry.get(elem.type)
    if (!desc) {
      // Sem descriptor conhecido: ignora silenciosamente
      return
    }

    // Contexto passado para o elemento (pode crescer no futuro)
    const ctx = {
      project,
      language: lang.id,
      environment: env,
      index,
    }

    // Se o descriptor tiver codeGenerator, usa; senão, ignora (sem erro)
    if (typeof desc.codeGenerator === 'function') {
      try {
        const code = desc.codeGenerator(elem, ctx)
        if (code && typeof code === 'string') {
          bodyLines.push(code.trim())
        }
      } catch (err) {
        // Falha em um elemento não deve quebrar o resto
        console.warn(`[generateProjectCode] erro em ${elem.type}:`, err)
      }
    }
  })

  // ===== ENVOLVER EM BEGIN/END CORRETOS =====
  const documentLines = [
    ...preambleLines,
    '\\begin{document}',
    `\\begin{${env}}`,
    ...bodyLines,
    `\\end{${env}}`,
    '\\end{document}',
    '',
  ]

  return documentLines.join('\n')
}
