import "./potentiometer.js";
import "./ammeter.js";
import "./pnj.js";
import "./fuse.js";
import "./resistor.js";
import "./switch_closed.js";
import "./diode.js";
import "./euroresistor.js";
import "./ohmmeter.js";
import "./ground.js";
import "./capacitor.js";
import "./relay_spdt.js";
import "./thermistor.js";
import "./zener.js";
import "./isource.js";
import "./usresistor.js";
import "./capacitor_polar.js";
import "./voltmeter.js";
import "./opamp.js";
import "./inductor.js";
import "./vsource.js";
import "./npn.js";
import "./switch_open.js";

console.log("[CircuitTikZ] 22 elementos carregados");